# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143zMhdzy2UsUMjkw1GkVMa6NVpIathzT
"""



import random

participantes = []

print("=== CADASTRO DO SORTEIO ===")
print("Digite os nomes um por um. Quando terminar, digite 'fim' ou deixe em branco.\n")

while True:
    nome = input("Digite um nome para o sorteio: ").strip()

    if nome.lower() == 'fim' or nome == '':
        break

    participantes.append(nome)

if len(participantes) == 0:
    print("\nNenhum nome foi inserido. O sorteio foi cancelado.")
else:
    print(f"\nTotal de participantes cadastrados: {len(participantes)}")

    ganhador = random.choice(participantes)

    print("=" * 30)
    print(f"🎉 O GANHADOR(A) FOI: {ganhador} 🎉")
    print("=" * 30)